- hosts: all
  become: yes
  tasks:
    - name: Pull latest Docker images
      command: docker-compose pull

    - name: Run Docker Compose
      command: docker-compose up -d
      args:
        chdir: /path/to/your/project
